CREATE ROLE AGRICULTEUR;
CREATE ROLE TECHNICIEN;
CREATE ROLE INSPECTEUR;
CREATE ROLE ADMINISTRATEUR;
--AGRICULTEUR :peut inserer dans parcelle et  type_de culture  et peut voir les notifs et les rapports


GRANT SELECT ON RAPPORT TO AGRICULTEUR;
GRANT SELECT ON NOTIFICATION TO AGRICULTEUR;
--GRANT EXECUTE ON voir_interventions TO AGRICULTEUR;
-- GRANT EXECUTE ON voir_alertes_agriculteur TO AGRICULTEUR;
-- GRANT EXECUTE ON ajouter_parcelle TO AGRICULTEUR;
-- GRANT EXECUTE ON desactiver_parcelle TO AGRICULTEUR;
-- GRANT EXECUTE ON modifier_parcelle TO AGRICULTEUR;
--GRANT EXECUTE ON ajouter_type_culture TO AGRICULTEUR;
--GRANT EXECUTE ON voir_notification TO AGRICULTEUR
--Inspecteur peut voir les alertes et les rapports et les seuils 
GRANT SELECT ON ALERTE TO INSPECTEUR;
GRANT SElECT ON RAPPORT TO INSPECTEUR;
GRANT SELECT ON SEUIL_CULTURE TO INSPECTEUR;
--techniciens peut voir et update interventions
GRANT EXECUTE ON update_intervention_technicien  TO TECHNICIEN;
GRANT SELECT ON NOTIFICATION TO TECHNICIEN;


--GRANT EXECUTE ON voir_notifications TO TECHNICIEN
-- administrateur: tout les privileges
GRANT SELECT,INSERT ,UPDATE ,DELETE ON UTILISATEUR TO ADMINISTRATEUR;
GRANT SELECT ,INSERT,UPDATE,DELETE ON CHAMP TO ADMINISTRATEUR ;
GRANT SELECT,INSERT,UPDATE,DELETE ON TYPE_CULTURE TO ADMINISTRATEUR;
GRANT SELECT,INSERT,UPDATE,DELETE ON PARCELLE TO ADMINISTRATEUR;
GRANT SELECT ,INSERT,UPDATE,DELETE ON SEUIL_CULTURE TO ADMINISTRATEUR;
GRANT SELECT,INSERT,UPDATE,DELETE ON INTERVENTION TO ADMINISTRATEUR;
GRANT SELECT, INSERT, UPDATE, DELETE ON RAPPORT TO ADMINISTRATEUR;
GRANT SELECT, INSERT, UPDATE, DELETE ON NOTIFICATION TO ADMINISTRATEUR;

